# Install common software
sudo apt install gdebi
sudo apt install rednote
sudo apt install vlc
sudo apt install anki
sudo apt install mplayer
sudo apt install gnome-tweak-tool # 将caplock增加为esc
sudo apt install texmaker
sudo apt install font-manager
sudo apt install tmux
sudo apt install zsh
sudo apt install ipython
sudo apt install python-setup-tools
sudo apt install git
sudo apt install texlive-full

# Install root software
sudo apt install python-dev
sudo apt install gfortran
sudo apt install libssl-dev
sudo apt install libpcre3-dev
sudo apt install libglu1-mesa-dev
sudo apt install libglew-dev
sudo apt install libftgl-dev
sudo apt install libmysqlclient-dev
sudo apt install libfftw3-dev
sudo apt install libcfitsio3-dev
sudo apt install libgraphviz-dev
sudo apt install libavahi-compat-libdnssd-dev
sudo apt install libdap-dev
sudo apt install libxml2-dev
sudo apt install libgsl0-dev
sudo apt install libqt4-dev
sudo apt install libpnglite-dev
sudo apt install libafterimage-dev
sudo apt install libgmp-dev
sudo apt install libpq-dev
sudo apt install libsqlite3-dev
sudo apt install libiodbc2-dev
sudo apt install libdpm-dev
sudo apt install libavahi-core-dev

